### ISSUE TITLE
My keyboard stops working when i click the icon and there is none device paired

### ISSUE THREAD

**Issue by juansquintero** [HackeSta/polybar-kdeconnect#10]
If no device is connected and i click the icon it fezzes my pc, only the window that had focus in i3wm works,  any other thing just do not respond and i have to turn of my pc with the power button if i wanna use my pc

**Comment by haideralipunjabi** [comment]
Can you run the bar from terminal and check what output it gives there. The hanging only happens if polybar hangs.

**Comment by juansquintero** [comment]
it shows warn: No monitor specified, using "VGA1" error: Disabling tray manager (reason: Invalid position " ")
[config.txt](https://github.com/HackeSta/polybar-kdeconnect/files/3199586/config.txt)

**Comment by haideralipunjabi** [comment]
Well, the invalid position is due to not specifying one on line 31. Just comment it out. 
Does it work properly if you don't use the kdec module?

**Comment by juansquintero** [comment]
It worked
