### ISSUE TITLE
No such interface org.kde.kdeconnect.device.battery

### ISSUE THREAD

**Issue by slondr** [HackeSta/polybar-kdeconnect#13]
I think KDE removed the battery interface at some point recently. Launching the script now crashes my entire Polybar config.

qdbus reports no `battery` in /modules/kdeconnect/devices/[device id], only findmyphone, ping, sftp, share, and telephony.

**Comment by haideralipunjabi** [comment]
I checked their repository and they have released version 1.3.5 a few days ago. I found no evidence of removing anything battery related and their Android App from F-Droid also has battery stuff in it. I will upgrade to 1.3.5 myself soon and look into this.

**Comment by slondr** [comment]
Ah, I think something had screwed up on my system and was causing the battery service to crash. I got it working now, so this definitely isn't an upstream issue. Sorry for the inconvenience.
