### ISSUE TITLE
qbus-qt5

### ISSUE THREAD

**Issue by jajpater** [HackeSta/polybar-kdeconnect#19]
In Ubuntu you need 

`sudo apt get install qbus-qt5`

**Comment by haideralipunjabi** [comment]
Yes, I have mentioned in the README.md that qt5tools is a dependency.

**Comment by jajpater** [comment]
My point is that there is no qt5tools package on Buntu, you need qbus-qt5 instead.

**Comment by haideralipunjabi** [comment]
Oh, I didn't know that, thanks for informing
