### ISSUE TITLE
format error

### ISSUE THREAD

**Issue by AnnanKhan** [HackeSta/polybar-kdeconnect#21]
sorry if I am making a silly mistake.
when I run polybar with the module active
I get this error
`warn: Invalid color in formatting tag detected: "rg.freedesktop.DBus.Error.UnknownObject%{PR", using fallback "#ffff0000". This is an issue with one of your formatting tags. If it is not, please report this as a bug.
error: Failed to parse contents (reason: 1 unclosed action block(s))`
on Debian using KDE
maybe being on KDE is the issue here

**Comment by haideralipunjabi** [comment]
Have you modified the script somewhere?

**Comment by AnnanKhan** [comment]
No.
I scripted my own in python not as featured as yours of course, using qdbus.

**Comment by haideralipunjabi** [comment]
Typographical error most likely in some line
